### ISSUE TITLE
Getting Enable multithreading to use std::thread: Operation not permitted

### ISSUE THREAD

**Issue by rorossf** [doug65536/starve-check#1]
I was trying to your project to test my KVM VM with DigitalOcean, however I'm not familiar with C++ and couldn't find usage guide.

Ubuntu 14.05 x64

I'm getting the following error

```
Using all 1 CPUs
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)
```

**Comment by doug65536** [comment]
You probably need to pass `-pthread` on the compiler command line. How did you compile it? The included `CMakeLists.txt` adds `-pthread`.

Good point about lack of a guide. I will add build and usage instructions in the `README.md`.

**Comment by doug65536** [comment]
I am able to reproduce the issue you reported. I'm looking into it now.

**Comment by doug65536** [comment]
Sorry for the delay, I don't check GitHub as often as I should. Should be fixed now. You may need to clean all of the files out of the build directory (or remove it altogether) and configure and compile again for CMake to pick up the changes.

Thanks for reporting this issue!

**Comment by rorossf** [comment]
Thanks, this fixed the issue. Great tool and highly recommended to check starvation.
